### ISSUE TITLE
Adding duration parameter in the pod failure yaml

### ISSUE THREAD

**Issue by ajay-sc30** [vishrantgupta/chaos-mesh#1]
```
kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: vmware-cric
  name: energy-saving-pod-failure-870435
spec:
  selector:
    namespaces:
      - vmware-cric
    labelSelectors:
      rapp_cr: energy-saving
  mode: all
  action: pod-failure
  duration: 1m <------- Introducing this parameter with the MR
  gracePeriod: 0
```

Adding the `duration` parameter in the spec to simulate pod failure experiment for a particular duration.
